INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (3,2,'Plywood, 3/4, Oak')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (3,2,'Plywood, 1/2, Oak')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (2,3,'Sandpaper, Orbital, Velcro 60 grit')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (2,3,'Sandpaper, Orbital, Velcro 120 grit')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (2,3,'Sandpaper, Orbital, Velcro 220 grit')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (1,2,'2x4, Pine, Stain-Grade')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (1,2,'4x4, Pine, Stain Grade')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (4,2,'Slab, Hardwood')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (9,4,'Skilled Labor')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (9,4,'Unskilled Labor')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (5,3,'Wood glue')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (3,5,'Laquer, Semi-gloss')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (3,5,'Laquer, Satin')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (3,5,'Laquer, Gloss')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (3,5,'Polyurethane, Semi-gloss')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (3,5,'Polyurethane, Satin')
INSERT INTO CostItem (UnitOfMeasureId, CostCategoryId, ItemName) VALUES (3,5,'Polyurethane, Gloss')